### PR TITLE
fix(s3stream): fix concurrent upload LocalStreamRangeIndexCache

### PR DESCRIPTION
**Pull request by lifepuzzlefun**

### CODE REVIEW

**Comment by lifepuzzlefun** [comment]
```shell
[2024-08-21 18:59:12,965] WARN PutObject for object 63a594c8/_kafka_DMSoJVXo9Q/node-1004 fail, retry later (com.automq.stream.s3.operator.AbstractObjectStorage)
software.amazon.awssdk.services.s3.model.S3Exception: Uploading conflict, it must be someone uploading the same file. (Service: S3, Status Code: 412, Request ID: c4695d2c-b3f9-4d03-ac0f-94ce3b68c285, Extended Request ID: xnKEvVyI1BUN/knfP2qW9yd/3rSCGtj/K2GX+UHo0fkwl9xIKdjdDnccKrWBV5yCiQCnzl+NKfbmjcLOOK2nPw==)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:279)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:135)
	at software.amazon.awssdk.core.internal.metrics.BytesReadTrackingPublisher$BytesReadTracker.onComplete(BytesReadTrackingPublisher.java:74)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:519)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:254)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:77)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:375)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.complete(HandlerPublisher.java:447)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.handlerRemoved(HandlerPublisher.java:435)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:636)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:476)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:422)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:370)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:232)
```

**Comment by SCNieh** [comment]
@lifepuzzlefun Hi, meybe it's better to do something like:
1. make batchUpload method returns a cf to indicate whether the upload is completed (empty queue or flush to s3 succeed)
2. trigger batchUpload on start(), and schedule next batchUpload after a certain interval (like 10ms) when the cf completed
3. let the schedule task that priodically invokes flush() to invoke upload() instead, so batchUpload() will be the only place to trigger real uploading

**Comment by lifepuzzlefun** [comment]
agree. I'll submit the change later ~

**Comment by SCNieh** [comment]
fixed in https://github.com/AutoMQ/automq/pull/1904

**Pull request closed without merging**
