### PR TITLE
fix(s3stream): fix lock protect when update liveEpoch in S3ObjectsImage

### PR DESCRIPTION
**Pull request by lifepuzzlefun**
1. use RegistryRef to manage liveEpoch and lock access.
2. whenever access TimelinedHashMap the registry object lock should be hold. use RegistryRef.inLock

### CODE REVIEW

**Comment by lifepuzzlefun** [comment]
our long run cluster throw exception 
```
[2024-07-01 07:56:54,140] ERROR Encountered fatal fault: Unhandled fault in MetadataLoader#handleCommit. Last image offset was 67217386 (org.apache.kafka.server.fault.ProcessTerminatingFaultHandler)
java.lang.IllegalStateException: liveEpochs is empty
        at org.apache.kafka.image.S3ObjectsImage.deallocate(S3ObjectsImage.java:176)
        at io.netty.util.AbstractReferenceCounted.handleRelease(AbstractReferenceCounted.java:86)
        at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
        at org.apache.kafka.image.loader.MetadataLoader.maybePublishMetadata(MetadataLoader.java:360)
        at org.apache.kafka.image.loader.MetadataBatchLoader.applyDeltaAndUpdate(MetadataBatchLoader.java:272)
        at org.apache.kafka.image.loader.MetadataBatchLoader.maybeFlushBatches(MetadataBatchLoader.java:208)
        at org.apache.kafka.image.loader.MetadataLoader.lambda$handleCommit$1(MetadataLoader.java:375)
        at org.apache.kafka.queue.KafkaEventQueue$EventContext.run(KafkaEventQueue.java:131)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.handleEvents(KafkaEventQueue.java:214)
        at org.apache.kafka.queue.KafkaEventQueue$EventHandler.run(KafkaEventQueue.java:185)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lifepuzzlefun** [comment]
https://gist.github.com/lifepuzzlefun/6d2339d6f6f95ca936e144bc29855fb6#file-s3objectsimage-java-L161-L226 this test code if set LOCK to false the exception throws

**Comment by superhx** [comment]
Could you refactor S3ObjectsImage like S3StreamsMetadataImage by using RegistryRef

**Comment by lifepuzzlefun** [comment]
> Could you refactor S3ObjectsImage like S3StreamsMetadataImage by using RegistryRef

@superhx yeah, new code updated, if more unit test is needed please let me know.

**Review by superhx — APPROVED** [review]

**Pull request merged**
